flags: {}
extra-package-dbs: []
packages:
- '.'
- '../massiv/massiv-io'
resolver: lts-12.2
extra-deps:
- github: lehins/massiv
  commit: 9f6ae1050ad580443ccbeca2882def10d5c60a41
  subdirs:
    - massiv

